### ISSUE TITLE
add support for _index.md

### ISSUE THREAD

**Issue by pbexiga** [vaga/hugo-theme-m10c#119]
It would be useful to be able to use the content in _index.md if needed. This way you can customize the home page.

**Comment by pbexiga** [comment]
All we need to do is add the following to layouts\_default\list.html

>     <div class="post-content">
>       {{ .Content }}
>     </div>

the complete file should look like this:

> {{ define "main" }}
>   <article>
>     <h1>{{ .Title }}</h1>
> 
>     <div class="post-content">
>       {{ .Content }}
>     </div>
> 
>     <ul class="posts-list">
>       {{ range where .Paginator.Pages "Type" "!=" "page" }}
>         <li class="posts-list-item">
>           <a class="posts-list-item-title" href="{{ .Permalink }}">{{ .Title }}</a>
>           <span class="posts-list-item-description">
>             {{ partial "icon.html" (dict "ctx" $ "name" "calendar") }}
>             {{ .PublishDate.Format "Jan 2, 2006" }}
>             <span class="posts-list-item-separator">-</span>
>             {{ partial "icon.html" (dict "ctx" $ "name" "clock") }}
>             {{ .ReadingTime }} min read
>           </span>
>         </li>
>       {{ end }}
>     </ul>
>     {{ partial "pagination.html" $ }}
>   </article>
> {{ end }}

**Comment by vaga** [comment]
The issue has been resolved. See 8295ee808a8166a7302b781895f018d9cba20157
