### ISSUE TITLE
CodeOfConduct.md file for contributors 

### ISSUE THREAD

**Issue by Anuraj-IND** [vaga/hugo-theme-m10c#123]
CodeOfConduct.md generally contain set of rules and behaviors contributors must priorities while contributing to avoid spammy PRs and going again and again for same issue if its alright please let me make one codeofconduct.md file for this project and assign lables of hacktoberfest and gssoc

**Comment by Anuraj-IND** [comment]
@vaga respond to it please

**Comment by vaga** [comment]
Thank you for your suggestion regarding the Code of Conduct. However, I’m not interested in implementing one for this project at the moment.
