### ISSUE TITLE
What is the default network port for this theme?

### ISSUE THREAD

**Issue by tzkyard** [vaga/hugo-theme-m10c#13]
What is the default **network port** for hugo-theme-m10c ?    The default test website [http://localhost:1313/](http://localhost:1313/) is invalid.

**Comment by vaga** [comment]
The network port and the theme are unrelated topics.

If you follow the `README.md` instructions, you should have an empty blog: https://github.com/vaga/hugo-theme-m10c#getting-started

Otherwise,  can you copy/paste your command line and your `config.toml`?

**Comment by tzkyard** [comment]
Thank you for your prompt reply ! The problem has been solved by follow the
README.md instructions.
Thank you very much, the m10c theme is beautiful !!!

Fabien <notifications@github.com> 于2019年4月2日周二 上午1:59写道：
