### ISSUE TITLE
A question about font and front size

### ISSUE THREAD

**Issue by tzkyard** [vaga/hugo-theme-m10c#14]
I still have a question about How to customize font and font size ? It seems that what I can change now is the color.
```  
 # Green theme
  #[params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  primaryColor = "#dad865"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"  
```

**Comment by vaga** [comment]
For now, you can change only colors.

You can copy/paste `_base.scss` in your project root and edit the file.
```
cp themes/m10c/assets/css/_base.scss assets/css/_base.scss
```

Otherwise, you can fork the repository

**Comment by tzkyard** [comment]
OK， thank you for your reply！
