### ISSUE TITLE
Footnote links redirect to the homepage instead of their desired destionations

### ISSUE THREAD

**Issue by DarthEmpty** [vaga/hugo-theme-m10c#16]
It seems that footnote references, when placed in a markdown file, do not redirect the user to the relevant footnote but, instead, back to the home page.

It also seems that the return link in a footnote also redirects to the home page instead of redirecting back to the correct reference

e.g. if we had a post with the address `blog.com/posts/example` that contained the following:

```
I am referencing a footnote[^1]


[^1]: I am the footnote
```

Then both links, the reference and the return link, would be displayed correctly. However, the reference would redirect to `blog.com/#fn:1` instead of `blog.com/posts/example/#fn:1` and the return link would redirect to `blog.com/#fnref:1` instead of `blog.com/posts/example/#fnref:1`.

Thanks for your help.

**Comment by vaga** [comment]
I have the same issue on my test blog.
I tried with another theme and the issue is gone.

I'm working on it.

Thanks!
