### ISSUE TITLE
Does m10c work with RStudio

### ISSUE THREAD

**Issue by ogansser** [vaga/hugo-theme-m10c#20]
Hi, 
i try to run m10c with RStudio. It works but I cannot replace the avatar with my picture. Instead, there is the author name with a link to the committed server. 

Here is the config.toml:

baseURL = "https://www.gansser.info"
title = "my Site"
theme = "hugo-theme-m10c"
paginate = 10

[params]
  author = "Oliver Gansser"
  description = "Marketing - Research - Communication - Sales - Consumer-Typology"
  [[params.social]]
    name = "github"
    url = "https://github.com/gohugoio"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/gohugoio"

**Comment by ogansser** [comment]
Hi, have another question: 
Is it possible to place somewhere a kind of imprint?

Olli

**Comment by xeraa** [comment]
You can replace the image by putting your own one into `static/avatar.jpg` (the folder `static` is on the same level as `themes`) — this will overwrite the one from the theme.

To add a footer you'd IMO need to customize the template. Copy `themes/hugo-theme-m10c/layouts/_default/baseof.html` to `layouts/_default/baseof.html` and make your changes to that file. Maybe right before or after `</main>`, but that might also require some SCSS tweaking.

**Comment by ogansser** [comment]
replace the jpg with my own did not work. Maybe it has to do with my compiling with RStudio? Footer, I will try. Thanx

**Comment by xeraa** [comment]
Your editor won't make any difference. If you just run `hugo` it will generate a `public` folder with the output for you. There the avatar.jpg in the base folder (so `public/avatar.jpg`) should be the one from the `static/` folder.

**Comment by ogansser** [comment]
Yes. This works. But see on your own, how it looks like: www.gansser.de

**Comment by xeraa** [comment]
Yes, this is almost working.

The line that is causing the issue is https://github.com/vaga/hugo-theme-m10c/blob/master/layouts/_default/baseof.html#L20

Did you set the right `baseURL` in the configuration file? See https://github.com/vaga/hugo-theme-m10c/blob/master/exampleSite/config.toml#L1 for an example

**Comment by vaga** [comment]
How can you generate your website ?

At the moment, your `basURL` seems to be `/`.

I'm fixing double `/` in avatar src attribute.

**Comment by ogansser** [comment]
I generate it with blogdown in RStudio. 

`baseURL` doesn't change anything

**Comment by ogansser** [comment]
Hi guys, static folder is no deleted.

**Comment by ogansser** [comment]
great, it works. thanx!
