### ISSUE TITLE
Different titles

### ISSUE THREAD

**Issue by polleyg** [vaga/hugo-theme-m10c#23]
Awesome theme man. Nice work. I'm using it here -> https://polleyg.dev/

Is there any way to have the title seperate from what's displayed on the top of the blog posts? I my case, it display "polleyg.dev" twice.

<img width="681" alt="Screen Shot 2019-05-04 at 12 33 32 pm" src="https://user-images.githubusercontent.com/5554342/57172870-64023b00-6e69-11e9-9e24-c2fd5f5efab8.png">

My config:

<img width="932" alt="Screen Shot 2019-05-04 at 12 37 52 pm" src="https://user-images.githubusercontent.com/5554342/57172875-74b2b100-6e69-11e9-862a-73bcaf1f5654.png">

**Comment by vaga** [comment]
Thanks!

It's an actual behavior because, at the moment, the homepage uses list default layout (`_default/list.html` directory)
If you want, you can overwrite home page like this:
```
cp themes/m10c/layouts/_list.html layouts/home.html
```
and remove or replace <h1> tag

I should create more partials to improve the template customization.

**Comment by polleyg** [comment]
Thanks man.
