### ISSUE TITLE
R Markdown with plots

### ISSUE THREAD

**Issue by ogansser** [vaga/hugo-theme-m10c#24]
Hello, if I move an R markdown with plots on the server, the index file in the post folder will not be checked off. This is the case with .Rmd or .Rmarkdown.

With New Post markdown it works, but without plots.

e.g. with the following plot (default for R Markdown)

---
title: R Markdown
author: Oliver Gansser
date: '2019-05-11'
slug: r-markdown
categories: []
tags: []
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

This is an R Markdown document. Markdown is a simple formatting syntax for authoring HTML, PDF, and MS Word documents. For more details on using R Markdown see <http://rmarkdown.rstudio.com>.

When you click the **Knit** button a document will be generated that includes both content as well as the output of any embedded R code chunks within the document. You can embed an R code chunk like this:

```{r cars}
summary(cars)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

**Comment by vaga** [comment]
I never used  R Studio or R Markdown.
Your problem seems to be related to Hugo or R Studio.

**Comment by ogansser** [comment]
folder in public looks good an all plots are there, bunt index file does not work.

**Comment by vaga** [comment]
Where is the generated file?
Can you check the path of your generated file in HTML file?

**Comment by ogansser** [comment]
Ok, I tried R Markdown with the default theme lithium. Here it works: 

look up here:
http://gansser.info/

**Comment by ogansser** [comment]
with the theme m10c it works locally on my computer, but not on web space. same post, another theme:

look up here: 
www.gansser.de
