### ISSUE TITLE
Display `author` instead of `title`

### ISSUE THREAD

**Issue by lazystring** [vaga/hugo-theme-m10c#3]
Perhaps more of a suggestion. It would be nice to display `author` beneath the avatar and above the description instead of the page title.

**Comment by vaga** [comment]
Thanks for the suggestion! 👍 

It's defined like this because:

- the blog title should be in `<h1>` and `<title>` tag.
- an author or a blog can have a nickname. (like me)

If you don't need it, you can set same value in `params.author` and `title` property.

**Comment by Headline** [comment]
I think it's quite odd that the author name isn't below the avatar where I'd expect it. 

Very nice work on this, though. Looks great otherwise, totally cool with rolling my own:
```diff
--- a/layouts/_default/baseof.html
+++ b/layouts/_default/baseof.html
@@ -19,7 +19,7 @@
   <body>
     <header class="app-header">
       <a href="{{ .Site.BaseURL }}"><img class="app-header-avatar" src="{{ .Site.Params.avatar | default "avatar.jpg" | relURL }}" alt="{{ .Site.Params.author | default "John Doe" }}" /></a>
-      <span class="app-header-title">{{ .Site.Title }}</span>
+      <span class="app-header-title">{{ .Site.Params.author }}</span>
       {{- with .Site.Menus.main }}
       <nav class="app-header-menu">
         {{- range $key, $item := . }}
 ```
