### ISSUE TITLE
my linkedin icon didn't show up

### ISSUE THREAD

**Issue by tonyyang924** [vaga/hugo-theme-m10c#30]
```
baseURL = "https://tonyyang924.github.io/blog"
languageCode = "zh-TW"
title = "tonyyang924's programmer blog"
theme = "m10c"
disqusShortname = "tonyyang924"
paginate = 5
[params]
  author = "Tony Yang"
  description = "I'm an Android developer, based in Taipei, TW."
  [[params.social]]
    name = "github"
    url = "https://github.com/tonyyang924"
  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/tonyyang924/"
```
https://tonyyang924.github.io/blog/index.html

The social icon "linkedin" only show up on local when I type `hugo server -D` or open on my local.

![螢幕快照 2019-07-15 上午11 45 08](https://user-images.githubusercontent.com/12247447/61194740-0eae9980-a6f6-11e9-9570-cfa65d60d347.png)

but I upload static html to github pages that the linkedin icon didn't show up.

what happens to this? the icon not references by the other site, only use it by svg. It's weird... lol

**Comment by vaga** [comment]
LinkedIn icon is visible on your blog. (a problem with your cache?)

**Comment by tonyyang924** [comment]
![67440478_2320172064967069_8880292128014467072_n](https://user-images.githubusercontent.com/12247447/61264152-16397580-a7be-11e9-9b15-394d219c7c10.png)

god damn. It's weird... I can see linkedin icon on my mobile.
I have used chrome, google chrome private surfing, firefox and safari to see did it exists but not working.

**Comment by tonyyang924** [comment]
> LinkedIn icon is visible on your blog. (a problem with your cache?)

maybe that's my problem with my cache but I have no idea.. lol
@vaga 
can I ask you how to refresh/cleaning my cache? 
thank you!

**Comment by vaga** [comment]
To clean the browser cache, you should press Ctrl + Maj + R (or Cmd + Maj + R) when you're on your website.
Or, you can try with a private window in your browser.

**Comment by tonyyang924** [comment]
I found why browser not show linkedin icon. Because of this software "AdGuard".
