### ISSUE TITLE
Where to place avatar image?

### ISSUE THREAD

**Issue by psharma04** [vaga/hugo-theme-m10c#31]
In hugo, where should the avatar image be placed (which default directory)?

**Comment by vaga** [comment]
The avatar should be placed in `/static/avatar.jpg`.
You have an example with my blog repository: https://github.com/vaga/m10c-blog

Otherwise, you can change this path in `config.toml` with `avatar` property.
https://github.com/vaga/hugo-theme-m10c#configuration
