### ISSUE TITLE
Unable to change the theme colors

### ISSUE THREAD

**Issue by easybeau** [vaga/hugo-theme-m10c#33]
Hello, thanks for this theme.

I got the same issue : https://github.com/vaga/hugo-theme-m10c/issues/5. 

I'm unable to change the colors of the theme.
Best regards.

**Comment by easybeau** [comment]
Je parle français, on peut communiquer en français si vous voulez!

**Comment by easybeau** [comment]
Le seul moyen que j'ai trouvé de changer les couleurs du site est de modifier le fichier .content dans /themes/m10c/resources/_gen/assets/scss/css/.

**Comment by vaga** [comment]
You need the Hugo extended version.
https://gohugo.io/troubleshooting/faq/#i-get-tocss-this-feature-is-not-available-in-your-current-hugo-version

**Comment by easybeau** [comment]
Ok thanks!
