### ISSUE TITLE
how to resize pics?

### ISSUE THREAD

**Issue by leo81122** [vaga/hugo-theme-m10c#36]
Can't use 
![](image_url ?200x200)
or
![](image_url =200x200)
or
![](image_url){: "height = 200" "width = 200"}
or
<img src= "image_url" style= "zoom:90" / >
I can use those in vs code or typora, but can't in hugo!

**Comment by vaga** [comment]
You should add a shortcode:
https://stackoverflow.com/a/48217545/4267973
