### ISSUE TITLE
Support for Custom Menu Items

### ISSUE THREAD

**Issue by daniccan** [vaga/hugo-theme-m10c#37]
How to configure custom navigation items such as `About`, `tags` or `categories`?

**Comment by vaga** [comment]
For now, you can't add a custom links. You should overwrite `layouts/_default/baseof.html` in your own hugo website.

**Comment by TitaniumOne** [comment]
hello, how to configure my profile photo?

**Comment by vaga** [comment]
@TitaniumOne https://github.com/vaga/hugo-theme-m10c/issues/31#issuecomment-518026025
