### ISSUE TITLE
Font Awesome Headphones For Social

### ISSUE THREAD

**Issue by soehlert** [vaga/hugo-theme-m10c#4]
I wanted to set up a social link for my soundcloud (using the params like I did for github, twitter, et al) and I noticed that FA had a headphones icon. That seemed good enough for me. I was able to get it to work mostly, but the icon doesn't look quite right. I'm not sure if you have instructions on how you were able to get the other icons or if you wouldn't mind fixing up my code for it to make the image look a little cleaner.

I used this icon: https://fontawesome.com/icons/headphones?style=solid
And here's the code I came up with and put into layouts/partials/icon.html (didn't want to just do a PR since it didn't come out quite right)

```{{- else if (eq . "soundcloud") -}}
<svg  xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"  class="icon icon-headphones"><path d="M12 1.5c-6.633 0-12 5.367-12 12v2.25c0 .566.32 1.086.828 1.34l.676.34A5.248 5.248 0 0 0 6.75 22.5h1.125C8.496 22.5 9 21.996 9 21.375v-8.25C9 12.504 8.496 12 7.875 12H6.75A5.236 5.236 0 0 0 3 13.578V13.5c0-4.96 4.04-9 9-9s9 4.04 9 9v.078A5.236 5.236 0 0 0 17.25 12h-1.125c-.621 0-1.125.504-1.125 1.125v8.25c0 .621.504 1.125 1.125 1.125h1.125a5.248 5.248 0 0 0 5.246-5.07l.676-.34c.508-.254.828-.774.828-1.34V13.5c0-6.633-5.367-12-12-12zm0 0"></path></svg>

**Comment by vaga** [comment]
The main problem is that Feather icons have not the same shape as Awesome icons.
I prefer to keep Feather icons. I don't have any solutions except to fork this repository and to add fontawesome like you say.

I should write a script to include all Feather icons in this file `layouts / partials / icon.html`.

**Comment by soehlert** [comment]
Thanks for the info. I didn't realize they were different icons, that explains a lot! I like the feather icons better, too then. Looks like feather has a headphones icon as well so I'll just switch to using that. 

That script sounds like an awesome idea, feel free to close this one, or leave it open if you want to use it to track that script.
