### ISSUE TITLE
telegram icon

### ISSUE THREAD

**Issue by keylogthis** [vaga/hugo-theme-m10c#41]
The telegram icon works in efa65a45d2 but then the RSS icon doesn't work. Also the telegram icon doesn't work outside of efa65a45d2.

**Comment by vaga** [comment]
I made a script to retrieve all feather icons and i stopped to add manually requested icons.
If you want an Telegram icon, you can use `send` icon.

Follow this link to show all available icons: https://feathericons.com/

**Comment by keylogthis** [comment]
Okay, thanks.
