### ISSUE TITLE
Cannot Change Theme Style

### ISSUE THREAD

**Issue by stuartmacfarlane** [vaga/hugo-theme-m10c#5]
I've been trying to use the alternative example styles in my config.toml however no matter how I use them (per your example or otherwise) I cannot get the theme to show anything other than green and grey.

Is this a known issue?

**Comment by vaga** [comment]
Hi,

I don't have this issue. 🤔  Show me your `config.toml`.

**Comment by stuartmacfarlane** [comment]
`baseURL = "https://stuartmacfarlane.github.io/"
languageCode = "en-gb"
title = "Stuart Macfarlane"
theme = "m10c"

[params]
  author = "Stuart Macfarlane"
  description = "IT Consultant, Magento Moderator, Gamer and Dad"

  [[params.social]]
    name = "github"
    url = "https://github.com/stuartmacfarlane"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/multiplay_stu"

  [params.style]
    darkestColor = "#d35050"
    darkColor = "#212121"
    primaryColor = "#ffffff"
    lightColor = "#a2a2a2"
    lightestColor = "#d3d3d3"
`

**Comment by stuartmacfarlane** [comment]
I even changed the default values in "m10c/assets/css/main.scss" and they still end up using the original generated ones... This is more than likely something I'm doing wrong as I'm new to hugo however I cannot for the life of me figure out where.

```
$darkest-color: {{ .Site.Params.style.darkestColor | default "#d35050" }};
$dark-color: {{ .Site.Params.style.darkColor | default "#212121" }};
$light-color: {{ .Site.Params.style.lightColor | default "#f5e3e0" }};
$lightest-color: {{ .Site.Params.style.lightestColor | default "#f5f5f5" }};
$primary-color: {{ .Site.Params.style.primaryColor | default "#fff" }};
```

**Comment by stuartmacfarlane** [comment]
Think I figured it out :)
You are using Hugo Extended version which means your repo contains your compiled version of the CSS in "m10c/resources/_gen/assets/scss/css/"

My version on windows is not extended and does not support the ability to re-generate the CSS as shown when I remove that folders contents:
```
Building sites … ERROR 2019/02/27 21:11:57 error: failed to transform resource: TOCSS: failed to transform "css/main.scss" (text/x-scss): this feature is not available in your current Hugo version
Total in 24 ms
```

I will try updating to extended version of Hugo!
