### ISSUE TITLE
Can you add article search function?

### ISSUE THREAD

**Issue by 6923403** [vaga/hugo-theme-m10c#50]
Article search

Sorry, i don’t know much about this, i tried to do it myself and didn't do it well

**Comment by vaga** [comment]
This feature is not implemented in this theme but you can extend it with a solution like [Algolia](https://www.algolia.com/).
With a quick search, I found some articles about Hugo and Algolia. (for example, https://harrycresswell.com/articles/hugo-algolia-2/)

**Comment by 6923403** [comment]
> 此主题未实现此功能，但您可以使用[Algolia之](https://www.algolia.com/)类的解决方案[对其进行扩展](https://www.algolia.com/)。
> 通过快速搜索，我找到了一些有关雨果和阿尔戈利亚的文章。（例如，https://harrycresswell.com/articles/hugo-algolia-2/）

Well, thank you
