### ISSUE TITLE
Request: pagination

### ISSUE THREAD

**Issue by agrrh** [vaga/hugo-theme-m10c#6]
Would be great to add pagination.

For now, there is none, only latest 10 posts are visible:

![screenshot from 2019-02-28 16-12-57](https://user-images.githubusercontent.com/1294495/53568780-dc036a80-3b73-11e9-8ae0-1608fe46471e.png)

Probably I failed to enable it?

**Comment by vaga** [comment]
You can checkout. Now, the pagination is available. 👍
