### ISSUE TITLE
How to make tags?

### ISSUE THREAD

**Issue by swpper** [vaga/hugo-theme-m10c#62]
How to make tags(list and count the number of articles) like the demo blog at https://themes.gohugo.io//theme/hugo-theme-m10c/tags/

**Comment by vaga** [comment]
Code is here:
https://github.com/vaga/hugo-theme-m10c/blob/master/layouts/_default/terms.html

You can add a link to this page in `config.toml`, here:
https://github.com/vaga/hugo-theme-m10c/blob/master/exampleSite/config.toml#L12

**Comment by swpper** [comment]
Thank you! I know  the reason, the .md file created by
`hugo new posts/example.md`
doesn`t have the tags property. 
```
---
title: "Test3"
date: 2021-02-24T10:46:53+08:00
draft: true
---
```
I add it and it works.
