### ISSUE TITLE
Twitter icon on bio not showing 

### ISSUE THREAD

**Issue by matthieugouel** [vaga/hugo-theme-m10c#77]
Hi 👋 

Thanks for this beautiful hugo theme! 
I noticed the twitter icon is not showing on the bio sidebar

```
  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/matthieugouel"
```

Example with your blog: 

<img width="312" alt="Capture d’écran 2021-12-26 à 00 55 09" src="https://user-images.githubusercontent.com/6132122/147395707-1c05a607-47db-43e2-a487-58601426c3b3.png">

**Comment by vaga** [comment]
Sorry for the delay...
It seems to be an issue in your `config.toml`.
Please link me your config.toml if you still get the error.
