### ISSUE TITLE
Module Error

### ISSUE THREAD

**Issue by bocciaman** [vaga/hugo-theme-m10c#93]
I get the error "module "m10c" not found; either add it as a Hugo Module or store it in "/Users/myname".: module does not exist" when I run the hugo server command. Can you tell me how to fix it?

**Comment by aidowu** [comment]
I ran into similar issues. To fix this, comment out or remove the line -> themesDir = "../.." <- in your config.toml file.

**Comment by bocciaman** [comment]
I've moved away from this theme.
