### ISSUE TITLE
--minify breaks space between elements

### ISSUE THREAD

**Issue by QuAzI** [vaga/hugo-theme-m10c#96]
With --minify
![image](https://user-images.githubusercontent.com/1897605/201080138-90838c45-300a-4805-bb57-1aae825ed54f.png)

Without --minify
![image](https://user-images.githubusercontent.com/1897605/201080157-799a1b88-11ad-4bba-848c-cabaa5ded781.png)

As @pamubay said 
> `That's correct behavior, it's <div> vs <div> elements. div is block-element`

https://github.com/gohugoio/hugo/issues/10424

**Comment by vaga** [comment]
Give it a try with PR #98

**Comment by QuAzI** [comment]
Looks better! Even in articles
![image](https://user-images.githubusercontent.com/1897605/201483789-8fd1e9f6-4ae6-4b2a-9907-150a08f1d68f.png)

![image](https://user-images.githubusercontent.com/1897605/201483799-0781a3e2-c05c-4c04-a030-bc504004d8d7.png)

Thanks a lot

**Comment by vaga** [comment]
Nice! Thanks
